---
kind: pipeline
type: docker
name: style

platform:
  os: linux
  arch: amd64

steps:
- name: drone fmt
  image: letfn/drone
  settings:
    task: fmt

- name: drone lint
  image: letfn/drone
  settings:
    task: lint

...
