version: '3.7'

services:
  traefik:
    image: defn/traefik
    command:
      - --providers.file.directory=/etc/traefik
      - --providers.file.watch=true
      - --providers.consulcatalog=true
      - --providers.consulcatalog.exposedbydefault=false
      - --providers.consulcatalog.endpoint.address=${CONSUL_IP}:8500
      - --providers.consulcatalog.endpoint.scheme=http
      - --providers.consulcatalog.endpoint.datacenter=${CONSUL_DC}
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.usebindportip=false
      - --certificatesresolvers.cloudflare.acme.email=kitt@defn.us
      - --certificatesresolvers.cloudflare.acme.storage=/etc/traefik/certs/acme.json
      - --certificatesresolvers.cloudflare.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --entrypoints.http.address=:80
      - --entrypoints.http.proxyprotocol.insecure
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.permanent=false
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls=true
      - --entrypoints.https.http.tls.certresolver=cloudflare
      - --entrypoints.https.http.tls.domains[0].main=${KITT_DOMAIN}
      - --entrypoints.https.http.tls.domains[0].sans=*.${KITT_DOMAIN}
      - --entrypoints.https.proxyprotocol.insecure
      - --entrypoints.https.http.middlewares=traefik-forward-auth@docker
      - --api.dashboard
      - --api
      - --serverstransport.insecureskipverify=true
      - --log.level=ERROR
      - --accesslog=true
    env_file: ./.env
    networks:
      default:
        ipv4_address: ${KITT_NETWORK_PREFIX}.100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${TRAEFIK_MOUNT}/traefik/kitt.toml:/etc/traefik/kitt.toml
      - ${TRAEFIK_MOUNT}/traefik/certs:/etc/traefik/certs
    labels:
      - "app=traefik"
      - "zone=kitt"
      - "SERVICE_NAME=traefik"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-api.entrypoints=https"
      - "traefik.http.routers.traefik-api.rule=Host(`traefik.${KITT_DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-api.service=api@internal"
      - "traefik.http.services.traefik-api.loadbalancer.server.port=80"
      - "traefik.http.routers.traefik-dash.entrypoints=https"
      - "traefik.http.routers.traefik-dash.rule=Host(`traefik.${KITT_DOMAIN}`)"
      - "traefik.http.routers.traefik-dash.service=dashboard@internal"
      - "traefik.http.services.traefik-dash.loadbalancer.server.port=80"
    ports:
      - 443:443

  traefik-forward-auth:
    image: defn/traefik-forward-auth
    command: [ "--match-whitelist-or-domain" ]
    env_file: ./.env.auth
    labels:
      - "zone=kitt"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-forward-auth.entrypoints=https"
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`auth.${KITT_DOMAIN}`)"
      - "traefik.http.routers.traefik-forward-auth.middlewares=traefik-forward-auth"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
    depends_on:
      - traefik

networks:
  default:
    external:
      name: kitt_default
