[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[http]
  [http.routers]
    [http.routers.consul]
      service = "consul"
      entrypoints = ["https"]
      rule = "HostRegexp(`consul.{domain:.+}`)"

  [http.services]
    [http.services.consul.loadBalancer]
      [[http.services.consul.loadBalancer.servers]]
        url = "http://169.254.32.1:8500/"
